In [8]:
import numpy as np
import cv2

In [47]:
for i in range(19):
    img_path = 50+i
    img = cv2.imread('./sub_set_images/000%s.ppm' %img_path)
    gray= cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    kp, des = sift.detectAndCompute(gray,None)
    print(des)

None
[[  3.   1.   0.   0.   0.   0.  31.  61.   5.   4.   2.   2.   1.   4.
  101.  77.   0.   0.   0.   3.   3.  56. 125.   7.   0.   0.   0.   0.
    0.  63.  57.   0.  17.   1.   0.   0.   4.   5.  63.  91. 104.   3.
    0.   0.   4.  21.  90. 125.   9.   0.   0.   0.  77. 125.  87.  22.
    3.   3.   1.   1.  18.  57.  64.   2.  33.   4.   0.   9.  54.  14.
   12.  10. 125.  24.   0.   0.  13.  10.   3.  29.  51.   3.   0.   1.
  125. 103.   4.   8.  14.   8.   1.   2.  47.  38.  10.   3.  23.   2.
    0.   6.  43.  13.   3.  44. 125.   6.   0.   0.   3.   4.   5. 125.
   36.   1.   0.   3.  67. 125.  35.  32.   4.   0.   0.   5.  51. 112.
   20.   2.]
 [ 25.  43.   4.   8.  14.   0.   0.   1. 125. 125.   5.   5.   4.   0.
    0.   8.  31.  29.  30. 125.  62.   2.   0.   1.   9.   2.  18. 106.
   48.   7.   0.   1.  32.  20.  11.   4.  16.   5.   1.   8. 125.  27.
    4.  13.  19.   0.   0.  30.  40.   5.   5. 113. 125.   0.   0.   3.
   29.   3.   9.  43.  38.   0.   0.  22.  18.

[[66. 26.  0. ...  0.  0.  0.]
 [ 6.  7. 33. ...  4. 27. 26.]
 [36.  1.  0. ...  0.  2. 16.]
 ...
 [ 9.  7. 13. ...  0.  0.  0.]
 [28.  0.  2. ...  0.  0. 89.]
 [ 1.  3.  0. ...  0.  0.  2.]]
[[116.   0.   0. ...   0.   0.   3.]
 [123.  52.   2. ...  13.   3.   1.]
 [  7.  25.  54. ...   0.   0.   6.]
 ...
 [ 83.  48.   0. ...  27. 117.  51.]
 [  4.  45.  43. ...   0.   1. 158.]
 [  4.  59.  44. ...   0.   0.   0.]]
[[ 2.  3.  1. ...  1. 11. 56.]
 [ 3.  1. 11. ...  3.  1.  8.]
 [ 1.  3.  3. ...  0.  0.  5.]
 ...
 [ 1.  0.  0. ... 43. 21. 41.]
 [ 1.  1.  1. ... 15. 10.  6.]
 [ 0.  1.  0. ... 15.  8.  3.]]
[[  8.   1.   0. ...   0.   0.   0.]
 [106.   9.   2. ...   0.   0.   1.]
 [  2.   5.  21. ...   0.   0.   0.]
 ...
 [  0.   0.   6. ...  15.   0.   0.]
 [  0.   0.   0. ...   0.   0.   3.]
 [  0.   0.   0. ...   0.   0.   0.]]
[[  2.   2.  35. ...   0.   0.   5.]
 [  0.   1.   4. ...   0.   0.   0.]
 [112. 101.  29. ...   0.   0.   0.]
 ...
 [ 23.   6.   0. ...   0.  13. 133.]
 [  1. 

In [40]:
kp

[]